version: '3.8'
services: 
    api-service:
        build: .
        volumes: 
            - .:/usr/src/app/
        ports: 
            - 5001:5001
        environment: 
            PORT: 5001
            FLASK_DEBUG: 1   

